export const siteTaskDefinitions = [
  {
    key: 'listing',
    label: 'Explore',
    route: '/listing',
    description: 'Discover trusted and useful content.',
    contentType: 'listing',
    enabled: false,
  },
  {
    key: 'classified',
    label: 'Explore',
    route: '/classified',
    description: 'Browse timely updates and opportunities.',
    contentType: 'classified',
    enabled: false,
  },
  {
  key: 'article',
  label: 'Explore',
  route: '/article',
  description: 'Read curated insights and stories.',
  contentType: 'article',
  enabled: true,
},
  {
    key: 'image',
    label: 'Explore',
    route: '/image',
    description: 'Browse visual-first highlights and updates.',
    contentType: 'image',
    enabled: false,
  },
  {
    key: 'profile',
    label: 'Explore',
    route: '/profile',
    description: 'See people, teams, and trusted identities.',
    contentType: 'profile',
    enabled: false,
  },
  {
    key: 'sbm',
    label: 'Explore',
    route: '/sbm',
    description: 'Save and revisit valuable resources.',
    contentType: 'sbm',
    enabled: false,
  },
  {
    key: 'comment',
    label: 'Explore',
    route: '/blog',
    description: 'Follow discussion and community responses.',
    contentType: 'comment',
    enabled: false,
  },
  {
    key: 'pdf',
    label: 'Explore',
    route: '/pdf',
    description: 'Access downloadable and reference material.',
    contentType: 'pdf',
    enabled: false,
  },
  {
    key: 'org',
    label: 'Explore',
    route: '/team',
    description: 'Discover structured pages for groups and teams.',
    contentType: 'org',
    enabled: false,
  },
] as const

export const siteTaskViews = {
  listing: '/listing',
  classified: '/classified',
  article: '/article',
  image: '/image',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
